### ISSUE TITLE
After reconnecting server crashes

### ISSUE THREAD

**Issue by Letaryat** [Nereziel/cs2-WeaponPaints#6] opened 2023-11-08 08:59 UTC
First time logging to server works just fine but after reconnecting again server crashes. 
Console log:
```
Receiving C2S_CONNECT [protocol 13967 0 auth 3] from *ip address* Unhandled exception. System.InvalidOperationException: Nullable object must have a value.
at System.Nullable`1.get_Value()
at WeaponPaints.WeaponPaints.<>c__DisplayClass10_0.<OnEntitySpawned>b__0() in cs2-WeaponPaints-main\cs2-WeaponPaints-main\WeaponPaints.cs:line 32
```

As funny it might have sound but my knowledge of C# equals zero so I used a Chat GPT for that and somehow it works(?) I dunno if it should be that way and if there are any bugs but I reconnected a few times and server didn't crashed. Just added if with few statements. 

**Like I said I don't know if it is a proper solution but if someone needs it for now I think it works(?)**
```
Server.NextFrame(() =>
        {
            
        if (weapon.OwnerEntity.IsValid && 
            weapon.OwnerEntity.Value.EntityIndex.HasValue)
        {
            var pawn = new CBasePlayerPawn(NativeAPI.GetEntityFromIndex((int)weapon.OwnerEntity.Value.EntityIndex.Value.Value));
            if (!weapon.IsValid) return;
            if (!pawn.IsValid) return;
            var playerIndex = (int)pawn.Controller.Value.EntityIndex!.Value.Value;
            int weaponPaint = GetPlayersWeaponPaint(playerIndex, weapon.AttributeManager.Item.ItemDefinitionIndex);
            if (weaponPaint == 0) return;
            weapon.AttributeManager.Item.ItemIDLow = unchecked((uint)-1);
            weapon.AttributeManager.Item.ItemIDHigh = unchecked((uint)-1);
            weapon.FallbackPaintKit = weaponPaint;
            weapon.FallbackSeed = 0;
            weapon.FallbackWear = 0.0001f;
        }
        else
        {
            return;
        }
        });

**Comment by 1Mack** [comment] 2023-11-08 12:22
@Letaryat on your case, should be better:


`
Server.NextFrame(() =>
        {
            
        if (!weapon.OwnerEntity.IsValid || !weapon.OwnerEntity.Value.EntityIndex.HasValue) return;
        
            var pawn = new CBasePlayerPawn(NativeAPI.GetEntityFromIndex((int)weapon.OwnerEntity.Value.EntityIndex.Value.Value));
            if (!weapon.IsValid) return;
            if (!pawn.IsValid) return;
            var playerIndex = (int)pawn.Controller.Value.EntityIndex!.Value.Value;
            int weaponPaint = GetPlayersWeaponPaint(playerIndex, weapon.AttributeManager.Item.ItemDefinitionIndex);
            if (weaponPaint == 0) return;
            weapon.AttributeManager.Item.ItemIDLow = unchecked((uint)-1);
            weapon.AttributeManager.Item.ItemIDHigh = unchecked((uint)-1);
            weapon.FallbackPaintKit = weaponPaint;
            weapon.FallbackSeed = 0;
            weapon.FallbackWear = 0.0001f;
        
        });
`

**Comment by Nereziel** [comment] 2023-11-08 12:48
I couldnt reproduce the crash. One guy told me, he had crashes with cs2fixes. Do you have it too?

**Comment by Nereziel** [comment] 2023-11-08 12:57
@Letaryat Can you try with the latest version?

**Comment by blu133721** [comment] 2023-11-08 13:36
You are not the only one having the issue, I'm having it too.

I have the same error in the console, I thought that CS2Fixes was the problem here, but it turns out it isn't.

**Comment by Nereziel** [comment] 2023-11-08 13:55
@Letaryat should be fixed with that check from gpt.

**Comment by Letaryat** [comment] 2023-11-08 14:04
@Nereziel To be honest I think that version from @1Mack is better. 
Thank you very much!

**Closed** 2023-11-08 14:05 UTC
